version: '3.8'

services:
  gateway:
    build: ./gateway
    image: lynmoon/gateway:latest  # Usando tu usuario
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  auth-service:
    build: ./auth-service
    image: lynmoon/auth-service:latest # Usando tu usuario
    # ports:
    #   - "8081:8081"
    restart: always
    # environment:
    #   - SPRING_DATASOURCE_URL=...
    #   - SPRING_DATASOURCE_USERNAME=...
    #   - SPRING_DATASOURCE_PASSWORD=...

  employees-service:
    build: ./employees-service
    image: lynmoon/employees-service:latest # Usando tu usuario
    restart: always

  attendance-service:
    build: ./attendance-service
    image:  lynmoon/attendance-service:latest
    restart: always

  evaluation-service:
    build: ./evaluation-service
    image: lynmoon/evaluation-service:latest
    restart: always

  # ... agrega los otros microservicios ...

  # (Opcional) Si usas PostgreSQL:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: employees_db  # o el nombre de tu base de datos
    ports:
      - "5432:5432"  # SOLO si necesitas acceso directo desde fuera de Docker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: