version: '3.8'

services:
  # API Gateway
  api-gateway:
    image: lynmoon/my-api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - api-network
    depends_on:
      - auth-service
      - employee-service
      - attendance-service
      - evaluation-service

  # Servicio de autenticación
  auth-service:
    image: lynmoon/auth-service:latest
    container_name: auth-service
    ports:
      - "8081:8080"
    networks:
      - api-network

  # Servicio de empleados
  employee-service:
    image: lynmoon/employee-service:latest
    container_name: employee-service
    ports:
      - "8082:8080"
    networks:
      - api-network

  # Servicio de asistencia
  attendance-service:
    image: lynmoon/attendance-service:latest
    container_name: attendance-service
    ports:
      - "8083:8080"
    networks:
      - api-network

  # Servicio de evaluaciones
  evaluation-service:
    image: lynmoon/evaluation-service:latest
    container_name: evaluation-service
    ports:
      - "8084:8080"
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
