version: '3.8'
services:
  postgres-employee:
    image: postgres:latest
    container_name: postgres-employee
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    networks:
      - tarea

networks:
  tarea:
    driver: bridge
