version: '3.8'

services:
  postgres-employee:
    image: postgres:latest
    container_name: postgres-employee
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: employee_db  # Base de datos de empleados
    ports:
      - "5433:5432"  # Exponer el puerto 5433 para acceder desde fuera
    networks:
      - my-network
    volumes:
      - postgres_employee_data:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql  # Montar el archivo initdb.sql para inicializar la base de datos
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "employee_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  employee-service:
    image: lynmoon/employee-service:latest  # Reemplaza con la imagen de tu servicio
    container_name: employee-service
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      postgres-employee:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/employee_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_employee_data:  # Volumen para persistencia de la base de datos
