version: '3.8'

services:
  postgres-auth:
    image: postgres:latest
    container_name: postgres-auth
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: employee_db  # La base de datos de empleados
    ports:
      - "5432:5432"  # Centralizamos en un solo PostgreSQL
    networks:
      - my-network
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "employee_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  employee-service:
    build: .  # Asegúrate de que el Dockerfile está en la raíz
    container_name: employee-service
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      postgres-auth:
        condition: service_healthy  # Asegura que PostgreSQL esté listo
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/employee_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_auth_data:
