version: '3.8'
services:
  postgres-attendance:
    image: postgres:latest
    container_name: postgres-attendance
    environment:
      POSTGRES_DB: attendance_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    networks:
      - tarea

networks:
  tarea:
    driver: bridge
