version: '3.8'

services:
  postgres-evaluation:
    image: postgres:latest
    container_name: postgres-auth
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: evaluation_db
    ports:
      - "5435:5432"  # Exponer el puerto 5435 para acceder desde fuera
    networks:
      - my-network
    volumes:
      - postgres_evaluation_data:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql  # Montar el archivo initdb.sql para inicializar la base de datos
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  evaluation-service:
    build: .
    container_name: evaluation-service
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      postgres-evaluation:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/evaluation_db  # Usamos el nombre del servicio del contenedor
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_evaluation_data:
