version: '3.8'

services:
  postgres-auth:
    image: postgres:latest
    container_name: postgres-auth
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: evaluation_db  # La base de datos de evaluacion
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  evaluation-service:
    build: .
    container_name: evaluation-service
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      postgres-auth:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/evaluation_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_auth_data:
