server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: employees-service
          uri: http://localhost:4000
          predicates:
            - Path=/employees/**

        - id: attendance-service
          uri: http://localhost:5000
          predicates:
            - Path=/attendance/**

        - id: evaluations-service
          uri: http://localhost:6000
          predicates:
            - Path=/evaluations/**
