version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"  # Puerto de la base de datos PostgreSQL
    networks:
      - my-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  evaluation-service:
    build: ./evaluation-service  # Asegúrate de que esta ruta esté correcta
    container_name: evaluation-service
    restart: always
    ports:
      - "8084:8084"  # Puerto del microservicio de evaluación
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/evaluation_db  # La base de datos de evaluación
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data:
